/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MilitaryImport } from './routes/military'
import { Route as InformationImport } from './routes/information'
import { Route as GovernmentImport } from './routes/government'
import { Route as EconomyImport } from './routes/economy'
import { Route as DiplomacyImport } from './routes/diplomacy'
import { Route as IndexImport } from './routes/index'
import { Route as MilitaryIndexImport } from './routes/military/index'
import { Route as InformationIndexImport } from './routes/information/index'
import { Route as GovernmentIndexImport } from './routes/government/index'
import { Route as EconomyIndexImport } from './routes/economy/index'
import { Route as DiplomacyIndexImport } from './routes/diplomacy/index'
import { Route as MilitaryMapImport } from './routes/military/map'
import { Route as MilitaryLinksImport } from './routes/military/links'
import { Route as InformationNexusImport } from './routes/information/nexus'
import { Route as InformationMapImport } from './routes/information/map'
import { Route as InformationLinksImport } from './routes/information/links'
import { Route as InformationFediverseImport } from './routes/information/fediverse'
import { Route as GovernmentMapImport } from './routes/government/map'
import { Route as GovernmentLinksImport } from './routes/government/links'
import { Route as GovernmentClassImport } from './routes/government/class'
import { Route as EconomyMapImport } from './routes/economy/map'
import { Route as EconomyLinksImport } from './routes/economy/links'
import { Route as EconomyChartsImport } from './routes/economy/charts'
import { Route as DiplomacyMapImport } from './routes/diplomacy/map'
import { Route as DiplomacyLinksImport } from './routes/diplomacy/links'
import { Route as MilitaryMapIndexImport } from './routes/military/map/index'
import { Route as InformationNexusIndexImport } from './routes/information/nexus/index'
import { Route as InformationMapIndexImport } from './routes/information/map/index'
import { Route as InformationFediverseIndexImport } from './routes/information/fediverse/index'
import { Route as GovernmentMapIndexImport } from './routes/government/map/index'
import { Route as EconomyMapIndexImport } from './routes/economy/map/index'
import { Route as DiplomacyMapIndexImport } from './routes/diplomacy/map/index'
import { Route as InformationNexusProlewikiImport } from './routes/information/nexus/prolewiki'
import { Route as InformationNexusNatopediaImport } from './routes/information/nexus/natopedia'
import { Route as InformationNexusAnarchistlibraryImport } from './routes/information/nexus/anarchistlibrary'
import { Route as InformationNexus72TbulletinsImport } from './routes/information/nexus/72Tbulletins'
import { Route as InformationFediverseMastodonImport } from './routes/information/fediverse/mastodon'
import { Route as InformationFediverseLemmyImport } from './routes/information/fediverse/lemmy'
import { Route as EconomyMapIndustryImport } from './routes/economy/map/industry'
import { Route as EconomyMapEnergyImport } from './routes/economy/map/energy'
import { Route as DiplomacyMapEmbassyImport } from './routes/diplomacy/map/embassy'

// Create/Update Routes

const MilitaryRoute = MilitaryImport.update({
  id: '/military',
  path: '/military',
  getParentRoute: () => rootRoute,
} as any)

const InformationRoute = InformationImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRoute,
} as any)

const GovernmentRoute = GovernmentImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRoute,
} as any)

const EconomyRoute = EconomyImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRoute,
} as any)

const DiplomacyRoute = DiplomacyImport.update({
  id: '/diplomacy',
  path: '/diplomacy',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MilitaryIndexRoute = MilitaryIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MilitaryRoute,
} as any)

const InformationIndexRoute = InformationIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InformationRoute,
} as any)

const GovernmentIndexRoute = GovernmentIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovernmentRoute,
} as any)

const EconomyIndexRoute = EconomyIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EconomyRoute,
} as any)

const DiplomacyIndexRoute = DiplomacyIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiplomacyRoute,
} as any)

const MilitaryMapRoute = MilitaryMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => MilitaryRoute,
} as any)

const MilitaryLinksRoute = MilitaryLinksImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => MilitaryRoute,
} as any)

const InformationNexusRoute = InformationNexusImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => InformationRoute,
} as any)

const InformationMapRoute = InformationMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => InformationRoute,
} as any)

const InformationLinksRoute = InformationLinksImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => InformationRoute,
} as any)

const InformationFediverseRoute = InformationFediverseImport.update({
  id: '/fediverse',
  path: '/fediverse',
  getParentRoute: () => InformationRoute,
} as any)

const GovernmentMapRoute = GovernmentMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => GovernmentRoute,
} as any)

const GovernmentLinksRoute = GovernmentLinksImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => GovernmentRoute,
} as any)

const GovernmentClassRoute = GovernmentClassImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => GovernmentRoute,
} as any)

const EconomyMapRoute = EconomyMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => EconomyRoute,
} as any)

const EconomyLinksRoute = EconomyLinksImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => EconomyRoute,
} as any)

const EconomyChartsRoute = EconomyChartsImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => EconomyRoute,
} as any)

const DiplomacyMapRoute = DiplomacyMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DiplomacyRoute,
} as any)

const DiplomacyLinksRoute = DiplomacyLinksImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DiplomacyRoute,
} as any)

const MilitaryMapIndexRoute = MilitaryMapIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MilitaryMapRoute,
} as any)

const InformationNexusIndexRoute = InformationNexusIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InformationNexusRoute,
} as any)

const InformationMapIndexRoute = InformationMapIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InformationMapRoute,
} as any)

const InformationFediverseIndexRoute = InformationFediverseIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InformationFediverseRoute,
} as any)

const GovernmentMapIndexRoute = GovernmentMapIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovernmentMapRoute,
} as any)

const EconomyMapIndexRoute = EconomyMapIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EconomyMapRoute,
} as any)

const DiplomacyMapIndexRoute = DiplomacyMapIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiplomacyMapRoute,
} as any)

const InformationNexusProlewikiRoute = InformationNexusProlewikiImport.update({
  id: '/prolewiki',
  path: '/prolewiki',
  getParentRoute: () => InformationNexusRoute,
} as any)

const InformationNexusNatopediaRoute = InformationNexusNatopediaImport.update({
  id: '/natopedia',
  path: '/natopedia',
  getParentRoute: () => InformationNexusRoute,
} as any)

const InformationNexusAnarchistlibraryRoute =
  InformationNexusAnarchistlibraryImport.update({
    id: '/anarchistlibrary',
    path: '/anarchistlibrary',
    getParentRoute: () => InformationNexusRoute,
  } as any)

const InformationNexus72TbulletinsRoute =
  InformationNexus72TbulletinsImport.update({
    id: '/72Tbulletins',
    path: '/72Tbulletins',
    getParentRoute: () => InformationNexusRoute,
  } as any)

const InformationFediverseMastodonRoute =
  InformationFediverseMastodonImport.update({
    id: '/mastodon',
    path: '/mastodon',
    getParentRoute: () => InformationFediverseRoute,
  } as any)

const InformationFediverseLemmyRoute = InformationFediverseLemmyImport.update({
  id: '/lemmy',
  path: '/lemmy',
  getParentRoute: () => InformationFediverseRoute,
} as any)

const EconomyMapIndustryRoute = EconomyMapIndustryImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => EconomyMapRoute,
} as any)

const EconomyMapEnergyRoute = EconomyMapEnergyImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => EconomyMapRoute,
} as any)

const DiplomacyMapEmbassyRoute = DiplomacyMapEmbassyImport.update({
  id: '/embassy',
  path: '/embassy',
  getParentRoute: () => DiplomacyMapRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/diplomacy': {
      id: '/diplomacy'
      path: '/diplomacy'
      fullPath: '/diplomacy'
      preLoaderRoute: typeof DiplomacyImport
      parentRoute: typeof rootRoute
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyImport
      parentRoute: typeof rootRoute
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentImport
      parentRoute: typeof rootRoute
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationImport
      parentRoute: typeof rootRoute
    }
    '/military': {
      id: '/military'
      path: '/military'
      fullPath: '/military'
      preLoaderRoute: typeof MilitaryImport
      parentRoute: typeof rootRoute
    }
    '/diplomacy/links': {
      id: '/diplomacy/links'
      path: '/links'
      fullPath: '/diplomacy/links'
      preLoaderRoute: typeof DiplomacyLinksImport
      parentRoute: typeof DiplomacyImport
    }
    '/diplomacy/map': {
      id: '/diplomacy/map'
      path: '/map'
      fullPath: '/diplomacy/map'
      preLoaderRoute: typeof DiplomacyMapImport
      parentRoute: typeof DiplomacyImport
    }
    '/economy/charts': {
      id: '/economy/charts'
      path: '/charts'
      fullPath: '/economy/charts'
      preLoaderRoute: typeof EconomyChartsImport
      parentRoute: typeof EconomyImport
    }
    '/economy/links': {
      id: '/economy/links'
      path: '/links'
      fullPath: '/economy/links'
      preLoaderRoute: typeof EconomyLinksImport
      parentRoute: typeof EconomyImport
    }
    '/economy/map': {
      id: '/economy/map'
      path: '/map'
      fullPath: '/economy/map'
      preLoaderRoute: typeof EconomyMapImport
      parentRoute: typeof EconomyImport
    }
    '/government/class': {
      id: '/government/class'
      path: '/class'
      fullPath: '/government/class'
      preLoaderRoute: typeof GovernmentClassImport
      parentRoute: typeof GovernmentImport
    }
    '/government/links': {
      id: '/government/links'
      path: '/links'
      fullPath: '/government/links'
      preLoaderRoute: typeof GovernmentLinksImport
      parentRoute: typeof GovernmentImport
    }
    '/government/map': {
      id: '/government/map'
      path: '/map'
      fullPath: '/government/map'
      preLoaderRoute: typeof GovernmentMapImport
      parentRoute: typeof GovernmentImport
    }
    '/information/fediverse': {
      id: '/information/fediverse'
      path: '/fediverse'
      fullPath: '/information/fediverse'
      preLoaderRoute: typeof InformationFediverseImport
      parentRoute: typeof InformationImport
    }
    '/information/links': {
      id: '/information/links'
      path: '/links'
      fullPath: '/information/links'
      preLoaderRoute: typeof InformationLinksImport
      parentRoute: typeof InformationImport
    }
    '/information/map': {
      id: '/information/map'
      path: '/map'
      fullPath: '/information/map'
      preLoaderRoute: typeof InformationMapImport
      parentRoute: typeof InformationImport
    }
    '/information/nexus': {
      id: '/information/nexus'
      path: '/nexus'
      fullPath: '/information/nexus'
      preLoaderRoute: typeof InformationNexusImport
      parentRoute: typeof InformationImport
    }
    '/military/links': {
      id: '/military/links'
      path: '/links'
      fullPath: '/military/links'
      preLoaderRoute: typeof MilitaryLinksImport
      parentRoute: typeof MilitaryImport
    }
    '/military/map': {
      id: '/military/map'
      path: '/map'
      fullPath: '/military/map'
      preLoaderRoute: typeof MilitaryMapImport
      parentRoute: typeof MilitaryImport
    }
    '/diplomacy/': {
      id: '/diplomacy/'
      path: '/'
      fullPath: '/diplomacy/'
      preLoaderRoute: typeof DiplomacyIndexImport
      parentRoute: typeof DiplomacyImport
    }
    '/economy/': {
      id: '/economy/'
      path: '/'
      fullPath: '/economy/'
      preLoaderRoute: typeof EconomyIndexImport
      parentRoute: typeof EconomyImport
    }
    '/government/': {
      id: '/government/'
      path: '/'
      fullPath: '/government/'
      preLoaderRoute: typeof GovernmentIndexImport
      parentRoute: typeof GovernmentImport
    }
    '/information/': {
      id: '/information/'
      path: '/'
      fullPath: '/information/'
      preLoaderRoute: typeof InformationIndexImport
      parentRoute: typeof InformationImport
    }
    '/military/': {
      id: '/military/'
      path: '/'
      fullPath: '/military/'
      preLoaderRoute: typeof MilitaryIndexImport
      parentRoute: typeof MilitaryImport
    }
    '/diplomacy/map/embassy': {
      id: '/diplomacy/map/embassy'
      path: '/embassy'
      fullPath: '/diplomacy/map/embassy'
      preLoaderRoute: typeof DiplomacyMapEmbassyImport
      parentRoute: typeof DiplomacyMapImport
    }
    '/economy/map/energy': {
      id: '/economy/map/energy'
      path: '/energy'
      fullPath: '/economy/map/energy'
      preLoaderRoute: typeof EconomyMapEnergyImport
      parentRoute: typeof EconomyMapImport
    }
    '/economy/map/industry': {
      id: '/economy/map/industry'
      path: '/industry'
      fullPath: '/economy/map/industry'
      preLoaderRoute: typeof EconomyMapIndustryImport
      parentRoute: typeof EconomyMapImport
    }
    '/information/fediverse/lemmy': {
      id: '/information/fediverse/lemmy'
      path: '/lemmy'
      fullPath: '/information/fediverse/lemmy'
      preLoaderRoute: typeof InformationFediverseLemmyImport
      parentRoute: typeof InformationFediverseImport
    }
    '/information/fediverse/mastodon': {
      id: '/information/fediverse/mastodon'
      path: '/mastodon'
      fullPath: '/information/fediverse/mastodon'
      preLoaderRoute: typeof InformationFediverseMastodonImport
      parentRoute: typeof InformationFediverseImport
    }
    '/information/nexus/72Tbulletins': {
      id: '/information/nexus/72Tbulletins'
      path: '/72Tbulletins'
      fullPath: '/information/nexus/72Tbulletins'
      preLoaderRoute: typeof InformationNexus72TbulletinsImport
      parentRoute: typeof InformationNexusImport
    }
    '/information/nexus/anarchistlibrary': {
      id: '/information/nexus/anarchistlibrary'
      path: '/anarchistlibrary'
      fullPath: '/information/nexus/anarchistlibrary'
      preLoaderRoute: typeof InformationNexusAnarchistlibraryImport
      parentRoute: typeof InformationNexusImport
    }
    '/information/nexus/natopedia': {
      id: '/information/nexus/natopedia'
      path: '/natopedia'
      fullPath: '/information/nexus/natopedia'
      preLoaderRoute: typeof InformationNexusNatopediaImport
      parentRoute: typeof InformationNexusImport
    }
    '/information/nexus/prolewiki': {
      id: '/information/nexus/prolewiki'
      path: '/prolewiki'
      fullPath: '/information/nexus/prolewiki'
      preLoaderRoute: typeof InformationNexusProlewikiImport
      parentRoute: typeof InformationNexusImport
    }
    '/diplomacy/map/': {
      id: '/diplomacy/map/'
      path: '/'
      fullPath: '/diplomacy/map/'
      preLoaderRoute: typeof DiplomacyMapIndexImport
      parentRoute: typeof DiplomacyMapImport
    }
    '/economy/map/': {
      id: '/economy/map/'
      path: '/'
      fullPath: '/economy/map/'
      preLoaderRoute: typeof EconomyMapIndexImport
      parentRoute: typeof EconomyMapImport
    }
    '/government/map/': {
      id: '/government/map/'
      path: '/'
      fullPath: '/government/map/'
      preLoaderRoute: typeof GovernmentMapIndexImport
      parentRoute: typeof GovernmentMapImport
    }
    '/information/fediverse/': {
      id: '/information/fediverse/'
      path: '/'
      fullPath: '/information/fediverse/'
      preLoaderRoute: typeof InformationFediverseIndexImport
      parentRoute: typeof InformationFediverseImport
    }
    '/information/map/': {
      id: '/information/map/'
      path: '/'
      fullPath: '/information/map/'
      preLoaderRoute: typeof InformationMapIndexImport
      parentRoute: typeof InformationMapImport
    }
    '/information/nexus/': {
      id: '/information/nexus/'
      path: '/'
      fullPath: '/information/nexus/'
      preLoaderRoute: typeof InformationNexusIndexImport
      parentRoute: typeof InformationNexusImport
    }
    '/military/map/': {
      id: '/military/map/'
      path: '/'
      fullPath: '/military/map/'
      preLoaderRoute: typeof MilitaryMapIndexImport
      parentRoute: typeof MilitaryMapImport
    }
  }
}

// Create and export the route tree

interface DiplomacyMapRouteChildren {
  DiplomacyMapEmbassyRoute: typeof DiplomacyMapEmbassyRoute
  DiplomacyMapIndexRoute: typeof DiplomacyMapIndexRoute
}

const DiplomacyMapRouteChildren: DiplomacyMapRouteChildren = {
  DiplomacyMapEmbassyRoute: DiplomacyMapEmbassyRoute,
  DiplomacyMapIndexRoute: DiplomacyMapIndexRoute,
}

const DiplomacyMapRouteWithChildren = DiplomacyMapRoute._addFileChildren(
  DiplomacyMapRouteChildren,
)

interface DiplomacyRouteChildren {
  DiplomacyLinksRoute: typeof DiplomacyLinksRoute
  DiplomacyMapRoute: typeof DiplomacyMapRouteWithChildren
  DiplomacyIndexRoute: typeof DiplomacyIndexRoute
}

const DiplomacyRouteChildren: DiplomacyRouteChildren = {
  DiplomacyLinksRoute: DiplomacyLinksRoute,
  DiplomacyMapRoute: DiplomacyMapRouteWithChildren,
  DiplomacyIndexRoute: DiplomacyIndexRoute,
}

const DiplomacyRouteWithChildren = DiplomacyRoute._addFileChildren(
  DiplomacyRouteChildren,
)

interface EconomyMapRouteChildren {
  EconomyMapEnergyRoute: typeof EconomyMapEnergyRoute
  EconomyMapIndustryRoute: typeof EconomyMapIndustryRoute
  EconomyMapIndexRoute: typeof EconomyMapIndexRoute
}

const EconomyMapRouteChildren: EconomyMapRouteChildren = {
  EconomyMapEnergyRoute: EconomyMapEnergyRoute,
  EconomyMapIndustryRoute: EconomyMapIndustryRoute,
  EconomyMapIndexRoute: EconomyMapIndexRoute,
}

const EconomyMapRouteWithChildren = EconomyMapRoute._addFileChildren(
  EconomyMapRouteChildren,
)

interface EconomyRouteChildren {
  EconomyChartsRoute: typeof EconomyChartsRoute
  EconomyLinksRoute: typeof EconomyLinksRoute
  EconomyMapRoute: typeof EconomyMapRouteWithChildren
  EconomyIndexRoute: typeof EconomyIndexRoute
}

const EconomyRouteChildren: EconomyRouteChildren = {
  EconomyChartsRoute: EconomyChartsRoute,
  EconomyLinksRoute: EconomyLinksRoute,
  EconomyMapRoute: EconomyMapRouteWithChildren,
  EconomyIndexRoute: EconomyIndexRoute,
}

const EconomyRouteWithChildren =
  EconomyRoute._addFileChildren(EconomyRouteChildren)

interface GovernmentMapRouteChildren {
  GovernmentMapIndexRoute: typeof GovernmentMapIndexRoute
}

const GovernmentMapRouteChildren: GovernmentMapRouteChildren = {
  GovernmentMapIndexRoute: GovernmentMapIndexRoute,
}

const GovernmentMapRouteWithChildren = GovernmentMapRoute._addFileChildren(
  GovernmentMapRouteChildren,
)

interface GovernmentRouteChildren {
  GovernmentClassRoute: typeof GovernmentClassRoute
  GovernmentLinksRoute: typeof GovernmentLinksRoute
  GovernmentMapRoute: typeof GovernmentMapRouteWithChildren
  GovernmentIndexRoute: typeof GovernmentIndexRoute
}

const GovernmentRouteChildren: GovernmentRouteChildren = {
  GovernmentClassRoute: GovernmentClassRoute,
  GovernmentLinksRoute: GovernmentLinksRoute,
  GovernmentMapRoute: GovernmentMapRouteWithChildren,
  GovernmentIndexRoute: GovernmentIndexRoute,
}

const GovernmentRouteWithChildren = GovernmentRoute._addFileChildren(
  GovernmentRouteChildren,
)

interface InformationFediverseRouteChildren {
  InformationFediverseLemmyRoute: typeof InformationFediverseLemmyRoute
  InformationFediverseMastodonRoute: typeof InformationFediverseMastodonRoute
  InformationFediverseIndexRoute: typeof InformationFediverseIndexRoute
}

const InformationFediverseRouteChildren: InformationFediverseRouteChildren = {
  InformationFediverseLemmyRoute: InformationFediverseLemmyRoute,
  InformationFediverseMastodonRoute: InformationFediverseMastodonRoute,
  InformationFediverseIndexRoute: InformationFediverseIndexRoute,
}

const InformationFediverseRouteWithChildren =
  InformationFediverseRoute._addFileChildren(InformationFediverseRouteChildren)

interface InformationMapRouteChildren {
  InformationMapIndexRoute: typeof InformationMapIndexRoute
}

const InformationMapRouteChildren: InformationMapRouteChildren = {
  InformationMapIndexRoute: InformationMapIndexRoute,
}

const InformationMapRouteWithChildren = InformationMapRoute._addFileChildren(
  InformationMapRouteChildren,
)

interface InformationNexusRouteChildren {
  InformationNexus72TbulletinsRoute: typeof InformationNexus72TbulletinsRoute
  InformationNexusAnarchistlibraryRoute: typeof InformationNexusAnarchistlibraryRoute
  InformationNexusNatopediaRoute: typeof InformationNexusNatopediaRoute
  InformationNexusProlewikiRoute: typeof InformationNexusProlewikiRoute
  InformationNexusIndexRoute: typeof InformationNexusIndexRoute
}

const InformationNexusRouteChildren: InformationNexusRouteChildren = {
  InformationNexus72TbulletinsRoute: InformationNexus72TbulletinsRoute,
  InformationNexusAnarchistlibraryRoute: InformationNexusAnarchistlibraryRoute,
  InformationNexusNatopediaRoute: InformationNexusNatopediaRoute,
  InformationNexusProlewikiRoute: InformationNexusProlewikiRoute,
  InformationNexusIndexRoute: InformationNexusIndexRoute,
}

const InformationNexusRouteWithChildren =
  InformationNexusRoute._addFileChildren(InformationNexusRouteChildren)

interface InformationRouteChildren {
  InformationFediverseRoute: typeof InformationFediverseRouteWithChildren
  InformationLinksRoute: typeof InformationLinksRoute
  InformationMapRoute: typeof InformationMapRouteWithChildren
  InformationNexusRoute: typeof InformationNexusRouteWithChildren
  InformationIndexRoute: typeof InformationIndexRoute
}

const InformationRouteChildren: InformationRouteChildren = {
  InformationFediverseRoute: InformationFediverseRouteWithChildren,
  InformationLinksRoute: InformationLinksRoute,
  InformationMapRoute: InformationMapRouteWithChildren,
  InformationNexusRoute: InformationNexusRouteWithChildren,
  InformationIndexRoute: InformationIndexRoute,
}

const InformationRouteWithChildren = InformationRoute._addFileChildren(
  InformationRouteChildren,
)

interface MilitaryMapRouteChildren {
  MilitaryMapIndexRoute: typeof MilitaryMapIndexRoute
}

const MilitaryMapRouteChildren: MilitaryMapRouteChildren = {
  MilitaryMapIndexRoute: MilitaryMapIndexRoute,
}

const MilitaryMapRouteWithChildren = MilitaryMapRoute._addFileChildren(
  MilitaryMapRouteChildren,
)

interface MilitaryRouteChildren {
  MilitaryLinksRoute: typeof MilitaryLinksRoute
  MilitaryMapRoute: typeof MilitaryMapRouteWithChildren
  MilitaryIndexRoute: typeof MilitaryIndexRoute
}

const MilitaryRouteChildren: MilitaryRouteChildren = {
  MilitaryLinksRoute: MilitaryLinksRoute,
  MilitaryMapRoute: MilitaryMapRouteWithChildren,
  MilitaryIndexRoute: MilitaryIndexRoute,
}

const MilitaryRouteWithChildren = MilitaryRoute._addFileChildren(
  MilitaryRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diplomacy': typeof DiplomacyRouteWithChildren
  '/economy': typeof EconomyRouteWithChildren
  '/government': typeof GovernmentRouteWithChildren
  '/information': typeof InformationRouteWithChildren
  '/military': typeof MilitaryRouteWithChildren
  '/diplomacy/links': typeof DiplomacyLinksRoute
  '/diplomacy/map': typeof DiplomacyMapRouteWithChildren
  '/economy/charts': typeof EconomyChartsRoute
  '/economy/links': typeof EconomyLinksRoute
  '/economy/map': typeof EconomyMapRouteWithChildren
  '/government/class': typeof GovernmentClassRoute
  '/government/links': typeof GovernmentLinksRoute
  '/government/map': typeof GovernmentMapRouteWithChildren
  '/information/fediverse': typeof InformationFediverseRouteWithChildren
  '/information/links': typeof InformationLinksRoute
  '/information/map': typeof InformationMapRouteWithChildren
  '/information/nexus': typeof InformationNexusRouteWithChildren
  '/military/links': typeof MilitaryLinksRoute
  '/military/map': typeof MilitaryMapRouteWithChildren
  '/diplomacy/': typeof DiplomacyIndexRoute
  '/economy/': typeof EconomyIndexRoute
  '/government/': typeof GovernmentIndexRoute
  '/information/': typeof InformationIndexRoute
  '/military/': typeof MilitaryIndexRoute
  '/diplomacy/map/embassy': typeof DiplomacyMapEmbassyRoute
  '/economy/map/energy': typeof EconomyMapEnergyRoute
  '/economy/map/industry': typeof EconomyMapIndustryRoute
  '/information/fediverse/lemmy': typeof InformationFediverseLemmyRoute
  '/information/fediverse/mastodon': typeof InformationFediverseMastodonRoute
  '/information/nexus/72Tbulletins': typeof InformationNexus72TbulletinsRoute
  '/information/nexus/anarchistlibrary': typeof InformationNexusAnarchistlibraryRoute
  '/information/nexus/natopedia': typeof InformationNexusNatopediaRoute
  '/information/nexus/prolewiki': typeof InformationNexusProlewikiRoute
  '/diplomacy/map/': typeof DiplomacyMapIndexRoute
  '/economy/map/': typeof EconomyMapIndexRoute
  '/government/map/': typeof GovernmentMapIndexRoute
  '/information/fediverse/': typeof InformationFediverseIndexRoute
  '/information/map/': typeof InformationMapIndexRoute
  '/information/nexus/': typeof InformationNexusIndexRoute
  '/military/map/': typeof MilitaryMapIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diplomacy/links': typeof DiplomacyLinksRoute
  '/economy/charts': typeof EconomyChartsRoute
  '/economy/links': typeof EconomyLinksRoute
  '/government/class': typeof GovernmentClassRoute
  '/government/links': typeof GovernmentLinksRoute
  '/information/links': typeof InformationLinksRoute
  '/military/links': typeof MilitaryLinksRoute
  '/diplomacy': typeof DiplomacyIndexRoute
  '/economy': typeof EconomyIndexRoute
  '/government': typeof GovernmentIndexRoute
  '/information': typeof InformationIndexRoute
  '/military': typeof MilitaryIndexRoute
  '/diplomacy/map/embassy': typeof DiplomacyMapEmbassyRoute
  '/economy/map/energy': typeof EconomyMapEnergyRoute
  '/economy/map/industry': typeof EconomyMapIndustryRoute
  '/information/fediverse/lemmy': typeof InformationFediverseLemmyRoute
  '/information/fediverse/mastodon': typeof InformationFediverseMastodonRoute
  '/information/nexus/72Tbulletins': typeof InformationNexus72TbulletinsRoute
  '/information/nexus/anarchistlibrary': typeof InformationNexusAnarchistlibraryRoute
  '/information/nexus/natopedia': typeof InformationNexusNatopediaRoute
  '/information/nexus/prolewiki': typeof InformationNexusProlewikiRoute
  '/diplomacy/map': typeof DiplomacyMapIndexRoute
  '/economy/map': typeof EconomyMapIndexRoute
  '/government/map': typeof GovernmentMapIndexRoute
  '/information/fediverse': typeof InformationFediverseIndexRoute
  '/information/map': typeof InformationMapIndexRoute
  '/information/nexus': typeof InformationNexusIndexRoute
  '/military/map': typeof MilitaryMapIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/diplomacy': typeof DiplomacyRouteWithChildren
  '/economy': typeof EconomyRouteWithChildren
  '/government': typeof GovernmentRouteWithChildren
  '/information': typeof InformationRouteWithChildren
  '/military': typeof MilitaryRouteWithChildren
  '/diplomacy/links': typeof DiplomacyLinksRoute
  '/diplomacy/map': typeof DiplomacyMapRouteWithChildren
  '/economy/charts': typeof EconomyChartsRoute
  '/economy/links': typeof EconomyLinksRoute
  '/economy/map': typeof EconomyMapRouteWithChildren
  '/government/class': typeof GovernmentClassRoute
  '/government/links': typeof GovernmentLinksRoute
  '/government/map': typeof GovernmentMapRouteWithChildren
  '/information/fediverse': typeof InformationFediverseRouteWithChildren
  '/information/links': typeof InformationLinksRoute
  '/information/map': typeof InformationMapRouteWithChildren
  '/information/nexus': typeof InformationNexusRouteWithChildren
  '/military/links': typeof MilitaryLinksRoute
  '/military/map': typeof MilitaryMapRouteWithChildren
  '/diplomacy/': typeof DiplomacyIndexRoute
  '/economy/': typeof EconomyIndexRoute
  '/government/': typeof GovernmentIndexRoute
  '/information/': typeof InformationIndexRoute
  '/military/': typeof MilitaryIndexRoute
  '/diplomacy/map/embassy': typeof DiplomacyMapEmbassyRoute
  '/economy/map/energy': typeof EconomyMapEnergyRoute
  '/economy/map/industry': typeof EconomyMapIndustryRoute
  '/information/fediverse/lemmy': typeof InformationFediverseLemmyRoute
  '/information/fediverse/mastodon': typeof InformationFediverseMastodonRoute
  '/information/nexus/72Tbulletins': typeof InformationNexus72TbulletinsRoute
  '/information/nexus/anarchistlibrary': typeof InformationNexusAnarchistlibraryRoute
  '/information/nexus/natopedia': typeof InformationNexusNatopediaRoute
  '/information/nexus/prolewiki': typeof InformationNexusProlewikiRoute
  '/diplomacy/map/': typeof DiplomacyMapIndexRoute
  '/economy/map/': typeof EconomyMapIndexRoute
  '/government/map/': typeof GovernmentMapIndexRoute
  '/information/fediverse/': typeof InformationFediverseIndexRoute
  '/information/map/': typeof InformationMapIndexRoute
  '/information/nexus/': typeof InformationNexusIndexRoute
  '/military/map/': typeof MilitaryMapIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diplomacy'
    | '/economy'
    | '/government'
    | '/information'
    | '/military'
    | '/diplomacy/links'
    | '/diplomacy/map'
    | '/economy/charts'
    | '/economy/links'
    | '/economy/map'
    | '/government/class'
    | '/government/links'
    | '/government/map'
    | '/information/fediverse'
    | '/information/links'
    | '/information/map'
    | '/information/nexus'
    | '/military/links'
    | '/military/map'
    | '/diplomacy/'
    | '/economy/'
    | '/government/'
    | '/information/'
    | '/military/'
    | '/diplomacy/map/embassy'
    | '/economy/map/energy'
    | '/economy/map/industry'
    | '/information/fediverse/lemmy'
    | '/information/fediverse/mastodon'
    | '/information/nexus/72Tbulletins'
    | '/information/nexus/anarchistlibrary'
    | '/information/nexus/natopedia'
    | '/information/nexus/prolewiki'
    | '/diplomacy/map/'
    | '/economy/map/'
    | '/government/map/'
    | '/information/fediverse/'
    | '/information/map/'
    | '/information/nexus/'
    | '/military/map/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diplomacy/links'
    | '/economy/charts'
    | '/economy/links'
    | '/government/class'
    | '/government/links'
    | '/information/links'
    | '/military/links'
    | '/diplomacy'
    | '/economy'
    | '/government'
    | '/information'
    | '/military'
    | '/diplomacy/map/embassy'
    | '/economy/map/energy'
    | '/economy/map/industry'
    | '/information/fediverse/lemmy'
    | '/information/fediverse/mastodon'
    | '/information/nexus/72Tbulletins'
    | '/information/nexus/anarchistlibrary'
    | '/information/nexus/natopedia'
    | '/information/nexus/prolewiki'
    | '/diplomacy/map'
    | '/economy/map'
    | '/government/map'
    | '/information/fediverse'
    | '/information/map'
    | '/information/nexus'
    | '/military/map'
  id:
    | '__root__'
    | '/'
    | '/diplomacy'
    | '/economy'
    | '/government'
    | '/information'
    | '/military'
    | '/diplomacy/links'
    | '/diplomacy/map'
    | '/economy/charts'
    | '/economy/links'
    | '/economy/map'
    | '/government/class'
    | '/government/links'
    | '/government/map'
    | '/information/fediverse'
    | '/information/links'
    | '/information/map'
    | '/information/nexus'
    | '/military/links'
    | '/military/map'
    | '/diplomacy/'
    | '/economy/'
    | '/government/'
    | '/information/'
    | '/military/'
    | '/diplomacy/map/embassy'
    | '/economy/map/energy'
    | '/economy/map/industry'
    | '/information/fediverse/lemmy'
    | '/information/fediverse/mastodon'
    | '/information/nexus/72Tbulletins'
    | '/information/nexus/anarchistlibrary'
    | '/information/nexus/natopedia'
    | '/information/nexus/prolewiki'
    | '/diplomacy/map/'
    | '/economy/map/'
    | '/government/map/'
    | '/information/fediverse/'
    | '/information/map/'
    | '/information/nexus/'
    | '/military/map/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiplomacyRoute: typeof DiplomacyRouteWithChildren
  EconomyRoute: typeof EconomyRouteWithChildren
  GovernmentRoute: typeof GovernmentRouteWithChildren
  InformationRoute: typeof InformationRouteWithChildren
  MilitaryRoute: typeof MilitaryRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiplomacyRoute: DiplomacyRouteWithChildren,
  EconomyRoute: EconomyRouteWithChildren,
  GovernmentRoute: GovernmentRouteWithChildren,
  InformationRoute: InformationRouteWithChildren,
  MilitaryRoute: MilitaryRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/diplomacy",
        "/economy",
        "/government",
        "/information",
        "/military"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/diplomacy": {
      "filePath": "diplomacy.tsx",
      "children": [
        "/diplomacy/links",
        "/diplomacy/map",
        "/diplomacy/"
      ]
    },
    "/economy": {
      "filePath": "economy.tsx",
      "children": [
        "/economy/charts",
        "/economy/links",
        "/economy/map",
        "/economy/"
      ]
    },
    "/government": {
      "filePath": "government.tsx",
      "children": [
        "/government/class",
        "/government/links",
        "/government/map",
        "/government/"
      ]
    },
    "/information": {
      "filePath": "information.tsx",
      "children": [
        "/information/fediverse",
        "/information/links",
        "/information/map",
        "/information/nexus",
        "/information/"
      ]
    },
    "/military": {
      "filePath": "military.tsx",
      "children": [
        "/military/links",
        "/military/map",
        "/military/"
      ]
    },
    "/diplomacy/links": {
      "filePath": "diplomacy/links.tsx",
      "parent": "/diplomacy"
    },
    "/diplomacy/map": {
      "filePath": "diplomacy/map.tsx",
      "parent": "/diplomacy",
      "children": [
        "/diplomacy/map/embassy",
        "/diplomacy/map/"
      ]
    },
    "/economy/charts": {
      "filePath": "economy/charts.tsx",
      "parent": "/economy"
    },
    "/economy/links": {
      "filePath": "economy/links.tsx",
      "parent": "/economy"
    },
    "/economy/map": {
      "filePath": "economy/map.tsx",
      "parent": "/economy",
      "children": [
        "/economy/map/energy",
        "/economy/map/industry",
        "/economy/map/"
      ]
    },
    "/government/class": {
      "filePath": "government/class.tsx",
      "parent": "/government"
    },
    "/government/links": {
      "filePath": "government/links.tsx",
      "parent": "/government"
    },
    "/government/map": {
      "filePath": "government/map.tsx",
      "parent": "/government",
      "children": [
        "/government/map/"
      ]
    },
    "/information/fediverse": {
      "filePath": "information/fediverse.tsx",
      "parent": "/information",
      "children": [
        "/information/fediverse/lemmy",
        "/information/fediverse/mastodon",
        "/information/fediverse/"
      ]
    },
    "/information/links": {
      "filePath": "information/links.tsx",
      "parent": "/information"
    },
    "/information/map": {
      "filePath": "information/map.tsx",
      "parent": "/information",
      "children": [
        "/information/map/"
      ]
    },
    "/information/nexus": {
      "filePath": "information/nexus.tsx",
      "parent": "/information",
      "children": [
        "/information/nexus/72Tbulletins",
        "/information/nexus/anarchistlibrary",
        "/information/nexus/natopedia",
        "/information/nexus/prolewiki",
        "/information/nexus/"
      ]
    },
    "/military/links": {
      "filePath": "military/links.tsx",
      "parent": "/military"
    },
    "/military/map": {
      "filePath": "military/map.tsx",
      "parent": "/military",
      "children": [
        "/military/map/"
      ]
    },
    "/diplomacy/": {
      "filePath": "diplomacy/index.tsx",
      "parent": "/diplomacy"
    },
    "/economy/": {
      "filePath": "economy/index.tsx",
      "parent": "/economy"
    },
    "/government/": {
      "filePath": "government/index.tsx",
      "parent": "/government"
    },
    "/information/": {
      "filePath": "information/index.tsx",
      "parent": "/information"
    },
    "/military/": {
      "filePath": "military/index.tsx",
      "parent": "/military"
    },
    "/diplomacy/map/embassy": {
      "filePath": "diplomacy/map/embassy.tsx",
      "parent": "/diplomacy/map"
    },
    "/economy/map/energy": {
      "filePath": "economy/map/energy.tsx",
      "parent": "/economy/map"
    },
    "/economy/map/industry": {
      "filePath": "economy/map/industry.tsx",
      "parent": "/economy/map"
    },
    "/information/fediverse/lemmy": {
      "filePath": "information/fediverse/lemmy.tsx",
      "parent": "/information/fediverse"
    },
    "/information/fediverse/mastodon": {
      "filePath": "information/fediverse/mastodon.tsx",
      "parent": "/information/fediverse"
    },
    "/information/nexus/72Tbulletins": {
      "filePath": "information/nexus/72Tbulletins.tsx",
      "parent": "/information/nexus"
    },
    "/information/nexus/anarchistlibrary": {
      "filePath": "information/nexus/anarchistlibrary.tsx",
      "parent": "/information/nexus"
    },
    "/information/nexus/natopedia": {
      "filePath": "information/nexus/natopedia.tsx",
      "parent": "/information/nexus"
    },
    "/information/nexus/prolewiki": {
      "filePath": "information/nexus/prolewiki.tsx",
      "parent": "/information/nexus"
    },
    "/diplomacy/map/": {
      "filePath": "diplomacy/map/index.tsx",
      "parent": "/diplomacy/map"
    },
    "/economy/map/": {
      "filePath": "economy/map/index.tsx",
      "parent": "/economy/map"
    },
    "/government/map/": {
      "filePath": "government/map/index.tsx",
      "parent": "/government/map"
    },
    "/information/fediverse/": {
      "filePath": "information/fediverse/index.tsx",
      "parent": "/information/fediverse"
    },
    "/information/map/": {
      "filePath": "information/map/index.tsx",
      "parent": "/information/map"
    },
    "/information/nexus/": {
      "filePath": "information/nexus/index.tsx",
      "parent": "/information/nexus"
    },
    "/military/map/": {
      "filePath": "military/map/index.tsx",
      "parent": "/military/map"
    }
  }
}
ROUTE_MANIFEST_END */
